"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export function ArticleEditor(){const params=useSearchParams();const id=params.get("id");const router=useRouter();const editor=useRef<HTMLDivElement>(null);const [form,setForm]=useState({title:"",slug:"",excerpt:"",category:"College Football",cover_image_url:"",is_top_story:false,status:"draft"});const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!id)return;createClient().from("articles").select("*").eq("id",id).single().then(({data})=>{if(data){setForm({...form,...data});if(editor.current)editor.current.innerHTML=data.body?.html||"";}})},[id]);
 const upload=async(file:File,bucket:string)=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Not signed in");const path=`${user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;};
 const cover=async(file?:File)=>{if(!file)return;setBusy(true);try{const url=await upload(file,"article-images");setForm(f=>({...f,cover_image_url:url}));}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const insertMedia=async(file?:File)=>{if(!file||!editor.current)return;setBusy(true);try{const video=file.type==="video/mp4";const url=await upload(file,video?"article-videos":"article-images");editor.current.focus();document.execCommand("insertHTML",false,video?`<video controls playsinline src="${url}"></video><p><br></p>`:`<img src="${url}" alt=""><p><br></p>`);}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const command=(cmd:string,value?:string)=>{editor.current?.focus();document.execCommand(cmd,false,value)};
 const save=async(status:string)=>{setBusy(true);setMessage("");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const payload={...form,slug:form.slug||slugify(form.title),status,author_id:user.id,body:{html:editor.current?.innerHTML||""},published_at:status==="published"?new Date().toISOString():null};let error;if(id){({error}=await supabase.from("articles").update(payload).eq("id",id));}else{({error}=await supabase.from("articles").insert(payload));}setBusy(false);if(error)setMessage(error.message);else{setMessage("Saved successfully.");router.push("/dashboard");router.refresh();}};
 return <div className="editor-layout"><section className="editor-form"><div className="editor-top"><div><small>ARTICLE EDITOR</small><h1>{id?"Edit Article":"Create New Article"}</h1></div><a href="/dashboard">← Dashboard</a></div><label>Headline<input value={form.title} onChange={e=>setForm({...form,title:e.target.value,slug:form.slug||slugify(e.target.value)})} placeholder="Enter article headline"/></label><div className="two-col"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>College Football</option><option>Breaking News</option><option>Recruiting</option><option>Transfer Portal</option><option>Coaching</option><option>Other News</option></select></label><label>URL Slug<input value={form.slug} onChange={e=>setForm({...form,slug:slugify(e.target.value)})}/></label></div><label>Preview Description<textarea value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})} maxLength={260}/></label><label>Cover Image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>cover(e.target.files?.[0])}/></label><label className="check"><input type="checkbox" checked={form.is_top_story} onChange={e=>setForm({...form,is_top_story:e.target.checked})}/> Feature in Top Stories</label><div className="toolbar"><button type="button" onClick={()=>command("bold")}><b>B</b></button><button type="button" onClick={()=>command("italic")}><i>I</i></button><button type="button" onClick={()=>command("formatBlock","h2")}>H2</button><button type="button" onClick={()=>command("insertUnorderedList")}>• List</button><button type="button" onClick={()=>{const u=prompt("Link URL");if(u)command("createLink",u)}}>Link</button><label className="upload-button">Image / MP4<input hidden type="file" accept="image/png,image/jpeg,image/webp,video/mp4" onChange={e=>insertMedia(e.target.files?.[0])}/></label></div><div ref={editor} className="rich-editor" contentEditable suppressContentEditableWarning data-placeholder="Write your story here…"/><div className="editor-actions"><button disabled={busy} onClick={()=>save("draft")} className="outline-button">Save Draft</button><button disabled={busy} onClick={()=>save("pending_review")} className="outline-button">Submit for Review</button><button disabled={busy} onClick={()=>save("published")} className="red-button">Publish</button></div>{message&&<p>{message}</p>}</section><aside className="preview"><small>LIVE PREVIEW</small><div className="preview-image" style={{backgroundImage:`url(${form.cover_image_url||"/top-tier-logo.png"})`}}/><span>{form.category}</span><h2>{form.title||"Your headline appears here"}</h2><p>{form.excerpt||"Your preview description appears here."}</p></aside></div>}
